# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
  include:
  - main
  - master/*
  - release/*
  exclude:
  - release/old*

pool:
  vmImage: 'ubuntu-latest'

variables:
  mySimpleVar: Rastko Sapic
  "my.dotted.var": dotted var value
  "my var with spaces": var with spaces value


steps:
- script: echo Hello, world to $(rale)!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
